### ISSUE TITLE
binary filename doesn't work as kubectl plugin

### ISSUE THREAD

**Issue by jpriebe** [runoncloud/kubectl-np-viewer#1]
I installed by downloading the release and putting the binary into my path.  `kubectl np-viewer` gives me this error:

    Error: unknown command "np-viewer" for "kubectl"

I had to rename the binary to `kubectl-np_viewer` (underscore, not dash).  This is probably not intuitive to users who don't have a lot of experience using or building kubectl plugins.

**Comment by jeanpbond** [comment]
Hi @jpriebe 

Thank you for your feedback, the file is named is `kubectl-np-viewer` because GoReleaser is using the project name. I have update the documentation and the installation command to rename the file as `kubectl-np_viewer`.
