### ISSUE TITLE
Possible CSV output ? 

### ISSUE THREAD

**Issue by anujp** [runoncloud/kubectl-np-viewer#3]
Hi !
Thanks for this great and handy krew plugin. 
This is not an issue with it, but wanted to know if it would be possible to allow for output to be in csv format. 

I can imagine this getting used as part of an admin tool, to view network policies

**Comment by jeanpbond** [comment]
Hi @anujp 

I create a enhancement issue (#4). I will possibly implement it in a near future. 

Don't hesitate if you want to contribute ;).
